### ISSUE TITLE
Please, add autocomplete function for variables starting with "$"

### ISSUE THREAD

**Issue by juniorporciuncula** [nojanath/SublimeKSP#126]

**Comment by magneto538** [comment]
You don’t need to have $ before a variable declaration with SublimeKSP. You should just not use it.

**Comment by juniorporciuncula** [comment]
I don't want to compile the code after every change. I want to code in .txt with the script in resources folder, its faster to code and see the changes on Kontakt.

**Comment by pryzmusic** [comment]
I hear you. This will require some research though, as the current behavior shows the list of completions just fine but clears the text unexpectedly when using the auto complete.

The behavior for what happens when you use the auto complete is not defined in the SublimeKSP  plugin but in Sublime itself. The SublimeKSP plugin seems to only be responsible for generating the list of potential completions and I can find no trace of code anywhere else that actually processes the completion. I'm wondering if I can somehow have the autocomplete parsing ignore prefixes like the `$` for completion in the first place.

**Comment by juniorporciuncula** [comment]
I can autocomplete variables with "$" on Sublime Text using other syntax, like C, C#, C++, Javascript...

**Comment by pryzmusic** [comment]
SublimeKSP was not written by the same person who wrote the parsers for the other languages.

**Comment by pryzmusic** [comment]
Fixed in 1.9.2!
