### ISSUE TITLE
Macro Pre-Processing Is Now Assuming Macro is Called (breaks a lot of my source code for other libs)

### ISSUE THREAD

**Issue by neblix** [nojanath/SublimeKSP#14]
![image](https://cloud.githubusercontent.com/assets/2980471/15525948/212b9fcc-21fc-11e6-84e1-17daaeb2578b.png)

There is nothing in this file except for this macro. However, this "define" keyword is expecting this macro to have been called. This seems to violate the convenience of SublimeKSP where it does not evaluate or parse code that is not ever being used.

**Comment by neblix** [comment]
I will be switching to "declare const" in the meantime; I should note that SublimeKSP ALREADY substitutes literal constants in for KSP constants. It has worked that way for a very long time.

**Comment by nojanath** [comment]
I assume this only happens if you use `define` in place of `declare const` inside of a macro.  Is that the case?  The title of this issue makes it sound like it's breaking your old code and I want to make sure that's not happening.

**Comment by neblix** [comment]
Sorry, I should clarify; I had changed older code to use "define" instead of "declare const" to be up to date, and it *then* breaks.

**Comment by SamWindell** [comment]
The define constant is different from the the declare constant. It is not meant to replace it, use define only when you have to. We needed a new constant that is substituted into literals before the macros are built in order to do functions like iterate_macro().

If we were to force the already existing declare const to be substituted earlier, code like this would break:
`declare const NUM := #value#`. I shall add to the wiki to make this clearer.


As a side note, the compiler _does_ evaluate and parse code that is never used. The removing of unused functions and variables is done nearly at the end of the compiling process.

**Comment by neblix** [comment]
Hi Sam,

It seems I was wrong, it looks like my "optimize compiled code" mark became unhecked when I updated the plugin. Sincerest apologies.
