### ISSUE TITLE
Digit limitation for float numbers

### ISSUE THREAD

**Issue by patrik-herman** [nojanath/SublimeKSP#173]
SublimeKSP seems to break with float numbers with more than 16 digits (both to the left and right from the decimal point combined), and the more I try to find the breaking point, the stranger results I get, for instance:
`4499999999999999.3` converts to `4499999999999999.5`, but `4499999999999999.2` converts to `4499999999999999.0`.

Larger numbers would get extra zeros, for instance:
`12345678901234567.0` converts to `12345678901234568000000000000000.0`.

**Comment by pryzmusic** [comment]
This is a limitation of floating point numbers in general. They don't have an infinite precision because they are stored in computer bytes, and there is only so much precision you can write before it is unable to store it all. If you type these numbers into a python console itself the exact same issues occur. 

![image](https://user-images.githubusercontent.com/2980471/99154725-e6cf9d00-267f-11eb-82b6-46fa22b39046.png)

**Comment by patrik-herman** [comment]
Sorry I didn't mention it before. The issue could be solved by importing `decimal` package.

If you do `from decimal import *` and then use `Decimal('4499999999999999.2')`, python returns exactly that (and you can use other operations with this data type) without any issues. I don't exactly know how the compiler works, but I'm confident this shouldn't be too difficult to implement, right?

**Comment by mkruselj** [comment]
Vanilla KSP itself is limited to 14 digits after the decimal point (which suggests that they are doubles internally, not floats). This is easy to test by just doing `message(~NI_MATH_PI)`, for example

Also the value limitation is still 32-bit signed, so largest representable number even for `real` variables in KSP is 2^31 - 1, so that's 10 digits.

**Comment by mkruselj** [comment]
Closing since there's nothing we can realistically do about this.
