### ISSUE TITLE
Indenting KSP code

### ISSUE THREAD

**Issue by zelasa** [nojanath/SublimeKSP#293]
An issue when indent KSP code with the command found in the command palette: Indenting: Reindent Lines. It almost worked, but when there is a SELECT - CASE in the code, it indent in a wrong way. Everything else looks great.
When I try Reindent in Menu -> Line -> Reindent, it works.

**Comment by mkruselj** [comment]
I cannot confirm over here...

**Comment by mkruselj** [comment]
KSP.tmPreferences, this is mildly improved by adjusting the `increase/decreaseIndentPattern` entries like so:

```
<key>increaseIndentPattern</key>
<string>\s*(on [a-z_]+|if|else|for|select|family|macro|function|while|taskfunc).*?$</string>
<key>decreaseIndentPattern</key>
<string>\s*(end (on|if|for|select|family|macro|function|while|taskfunc)|else).*?$</string>
```

**Comment by mkruselj** [comment]
This is now improved on sKSP side as much as possible (code within `case` branches won't indent further, as it stands, otherwise things are fine), but it seems things are super inconsistent in Sublime Text itself.

So, if you use the menu option to reindent, this is executed:

![image](https://user-images.githubusercontent.com/2393720/214632529-c0c19cfa-04f7-41e9-aff3-4e11e69fc94e.png)

And if you use the command palette action, this is executed:

![image](https://user-images.githubusercontent.com/2393720/214632583-7e4daccd-4811-4196-aa08-8d53fa487a29.png)


What I'm doing is I'm just binding this to Ctrl+Alt+L:

```
	{
		"keys": ["ctrl+alt+l"],
		"command": "reindent"
	},
```
