### ISSUE TITLE
Test Kontakt 5.6 version

### ISSUE THREAD

**Issue by SamWindell** [nojanath/SublimeKSP#40]
I have merged Nils's version 1.11 into my fork in the branch 5.6_Support https://github.com/SamWindell/SublimeKSP/tree/5.6_Support

However I haven't had time to test it yet. If anyone gets a chance to have a look that everything is working , I'm sure we can then push this to the package control version. 
Cheers!

**Comment by nojanath** [comment]
Nice!  My time is severely limited at the moment but as soon as I get the chance I can test some of the basics.

**Comment by mkruselj** [comment]
Perhaps ksp_builtins_data should be updated to match the :integer and similar definitions that's there in Nils' version. Also ksp_plugin.py can be updated so that compilation errors aren't thrown when you use some of those functions (for instance, load_array_str() or mf_insert_file() etc.)) and Extra syntax checks are enabled.

Attached are my suggested fixes.


[Sublime KSP 5.6 ED.zip](https://github.com/nojanath/SublimeKSP/files/539200/Sublime.KSP.5.6.ED.zip)

**Comment by mkruselj** [comment]
Also, sublime-syntax file needs to be updated so it supports new variable identifiers and functions/engine/control pars (for example it's missing new math constants, etc.)...

Attached!

[KSP syntax.zip](https://github.com/nojanath/SublimeKSP/files/539221/KSP.syntax.zip)

**Comment by SamWindell** [comment]
Thanks ED, I have added your suggestions.
