### ISSUE TITLE
Compilation does not take into account changes to files until they are saved.

### ISSUE THREAD

**Issue by raptor-666** [nojanath/SublimeKSP#406]
Previously, changes to files were taken into account in compilation without the need to save them. I assume this bug appeared because of the folder import support introduced in the last update.

**Comment by hinnar** [comment]
Confirm

**Comment by mkruselj** [comment]
No, this is an intentional change that sped up compile times by 10 seconds in some cases. It's a part of [this commit](https://github.com/nojanath/SublimeKSP/commit/2f29142978d862862a29a405b1614553fc019ac4).

**Comment by mkruselj** [comment]
OK after looking more into this, I don't think a revert to old behavior is possible, since imports are now handled by the sKSP preprocessor rather than the Sublime Text plugin layer (which was the case before). Which means the compiler has no knowledge of the text buffer views from SublimeKSP, it just does an `io.open()` and reads the file directly from the hard drive with whatever last saved state it had.
