### ISSUE TITLE
list compilation

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#58]
As of now, typing
```
list array_name
    array_entry_1
    array_entry_2
    array_entry_3
end list
```

is being compiled as
```
declare %array_name[3]
%array_name[0] := array_entry_1
%array_name[1] := array_entry_2
%array_name[2] := array_entry_3
```

In order to save lines of code and reduce overhead, it would be better to compile the array inline. So the result of compilation would be 
```
declare %array_name[3] := (array_entry_1, array_entry_2, array_entry_3)
```

This works only with numeric variables and constants. Text arrays need to be unrolled on separate lines.

**Comment by neblix** [comment]
It seems like there is some code in place that I can structurally alter to allow for this. Will look into it.

**Comment by mkruselj** [comment]
This wouldn't work if you mix and match literals with function calls and/or variables (which is what lists support). So, additional checks would need to happen in order to ensure smooth operation, and optimization only in the valid case where only literals (and constants and defines, I guess) are used to define a list.

**Comment by mkruselj** [comment]
Closing this one. Effort required doesn't balance out well with how useful the outcome would be.
