### ISSUE TITLE
import, noticed folder structure

### ISSUE THREAD

**Issue by Levitanus** [nojanath/SublimeKSP#85]
here is example:
![2017-12-24_16-58-15](https://user-images.githubusercontent.com/29713891/34325691-a5e887a6-e8cb-11e7-872e-adea526721fa.png)
there is tests_init.ksp module, which makes test enviropment:

```
{#pragma save_compiled_source <path>\current_test.txt}
import "../globals.ksp"

macro tests.init
	declare i
	make_perfview
end macro
```

with flexible test architecture I expect folowing tests logic:

```
import "../tests_init.ksp"
import "../../<tested module>.ksp"

on init 
	tests.init

	<test>
end on
```

but within this logic i receive exception 

```
---------------------------
Sublime Text
---------------------------
File does not exist or could not be read: '../globals.ksp' 
(try saving the files before compiling to get relative search paths right).
import "../globals.ksp"

../tests_init.ksp:8 
```

So, for solving this i have to rewrite tests_init.ksp this way:

```
{#pragma save_compiled_source <path>\current_test.txt}
import "../../globals.ksp"

macro tests.init
	declare i
	make_perfview
end macro
```

BUT. Here is deeper problem: If any of tested modules have import statement I'll receive exception. And this is killing much of possibilities.
I have not looked at code, solving imports, so I'm interesting, can this feature be realized?

**Comment by neblix** [comment]
This cannot be changed because people have designed their paths in such a way that the current way it works is utilized. If I fixed it to allow per-file relative path imports, it would break many projects and people would have to rewrite their imports.

That being said, the way it works is such that all paths are relative to the file that you execute the compilation on.

I recommend using a symlink for the absolute path instead of using relative paths, for example, in tests_init.ksp:

```
import "_PROJECT_DIR/globals.ksp"
```

and for a test in the UI folder:

```
import "_PROJECT_DIR/tests/tests_init.ksp"
import "_PROJECT_DIR/<tested-module>.ksp"
```

Forgive me if I got the folders wrong, your Sublime theme looks to be broken, as the folder "UI" is aligned horizontally the same as "tests_init.ksp" but there are items further to the right which suggests they are in the folder instead. I'm assuming "tests_init.ksp" is in the "tests" folder, and "globals.ksp" is in the root directory.

**Comment by neblix** [comment]
However, if people see a future where we want a new version of SublimeKSP which makes permanent, non-backwards compatible changes for the sake of progress, this is something I would definitely fix at that point. It would probably be a new Sublime package, such as "SublimeKSP 2".

**Comment by Levitanus** [comment]
Thank You very much for so useful and well-founded response!

**Comment by mkruselj** [comment]
I don't think this is ever happening, closing.
