### ISSUE TITLE
Allow passing CONTROL_PAR_ suffixes as parameters

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#92]
```
on init 
	some_func(hide, 100) 
end on

function some_func(par, value)
	ui_control -> par := value 
end function
```
In this case, the compiler wouldn't use 'par' as the parameter fed to the function during the call. It would use 'par' as a word, trying to compile 'CONTROL_PAR_PAR' instead of 'CONTROL_PAR_HIDE'. Would be amazing to avoid using macros for this purpose (thus, being able to declare local variables).

**Comment by neblix** [comment]
This is because `hide` is not an actual symbol but a pre-processed syntax which is then later converted into a code symbol. This is the problem with creating a language as a syntax extension instead of as an actual language.

The `->` isn't designed to evaluate the meaning or value of the word after it (in your case, `par`), it's simply a shorthand text substitution which up-cases the text and appends it to `CONTROL_PAR_`. It's a fixed, literal operation.

In other words, you may as well be asking for a way to reference a function with a variable name `perform_#variable#()". Methodically speaking, it's equivalent. For this, I use macros (it's what macros were created for in the first place).

Instead of making a solution for this problem directly, it can instead be fixed by something I'd like to do in the future, which is allowing for macro style #arg# arguments to function declarations, so you can mix and match what is code and what is a literal symbol.

**Comment by mkruselj** [comment]
Closing as we decided we won't be doing this.
