### ISSUE TITLE
iterate_macro not working when passing max value as a parameter

### ISSUE THREAD

**Issue by magneto538** [nojanath/SublimeKSP#95]
This wouldn't compile ('Invalid syntax in max value. This number must able to be evaluated to a single number at compile time; use only define constants, numbers or maths operations here.'):

```
on init
	some_macro(50)
end on 

macro some_macro(amount)
	iterate_macro(declare const N_#n# := #n#) := 0 to amount-1
end macro

```

This would compile:

```
on init
	some_macro(50)
end on 

macro some_macro(amount)
	iterate_macro(declare const N_#n# := #n#) := 0 to 50-1
end macro

```

Can this be fixed? It's pretty important - perhaps I'm missing something on my end.

**Comment by neblix** [comment]
As the error says, iterate_macro() can only be used in an explicit literal way and can’t be encapsulated inside something else using arguments.

I agree it’s primitive. I can try to expand its usage.

Also, I have no way of notifying the SublimeKSP users, since there is no email option; I am not able to work on the compiler for another few months. I have been having a very busy time finishing up my last year of university. My apologies for not getting through all these bugs.

**Comment by magneto538** [comment]
Thanks Nabeel. You've done an amazing work so far. Would love to help you, but I'm unfamiliar with Python so I'm not sure how I could be helpful. Best of luck with the university! Don't leave us, we need you! :P

**Comment by mkruselj** [comment]
He won't leave us, he's the only maintainer now, basically. And he has plans for SublimeKSP, once he's done with university. Gotta be patient :)
